version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: salary_dates_app
    volumes:
      - .:/app
    command: php artisan generate:payment-dates
